# 1. Numpy
- 고성능 과학계산을 위한 데이터분석 라이브러리
- 벡턴 산술연산을 제공하는 다차원 배열 제공(ndarray 클래스)
- 반복문 없이 전체 데이터 배열 연산 가능(sum(), sqrt(), mead())
- 선형대수, 난수(random수) 생성, 푸리에 변환

In [2]:
import numpy as np # numpy 불러오고 np라는 별칭지정

### 배열(array) 만들기

In [8]:
np.list1 =[1,2,3,4,5] #numpy에 있는 array라는 자료형
np.array(list1) #1차원 배열

array([1, 2, 3, 4, 5])

In [10]:
list2 = [[1,2,3], [4,5,6]] 
list2

[[1, 2, 3], [4, 5, 6]]

In [14]:
arr2 = np.array(list2) #2차원 배열
arr2

array([[1, 2, 3],
       [4, 5, 6]])

### 배열의 크기 확인

In [16]:
# shape : 배열의 크기
arr2.shape

(2, 3)

In [17]:
# size : 총 요소 개수 확인
arr2.size

6

In [18]:
# ndim : 배열의 차원
arr2.ndim

2

In [36]:
list3=[ [ [1,2], [3,4] ], [ [5,6], [7,8] ] ]
arr3 = np.array(list3)
print("배열의 크기 : ", arr3.shape)
print("배열의 요소 개수 : ", arr3.size)
print("배열의 차원 : ", arr3.ndim)

배열의 크기 :  (2, 2, 2)
배열의 요소 개수 :  8
배열의 차원 :  3


### array 생성

In [37]:
# 특정한 값으로 배열 생성
# np.zeros((행, 열)) 0으로 이루어진 배열 생성
np.zeros((3,4)) # 기본적인 타입은 float형 소수점임.

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
# 1로만 이루어진 배열 생성
np.ones((2,5)) 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
#np.full((크기, 원하는 값))
np.full((3,3), 3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

### 범위 배열 생성하기

In [43]:
# 1~50 범위 배열 생성1
# 1. 1~50 범위의 list

list1 = []
for i in range(1, 51):
    list1.append(i)

In [44]:
#2. list로 array 생성
np.array(list1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [45]:
# 1~50 범위 배열 생성2
# arange() 함수 - 배열 형태로 바로 범위 지정하는 함수
np.arange(1,51)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

### 난수 배열 생성하기

In [46]:
#랜덤 값 생성하기
#0~1사이 값
np.random.rand(2, 3)

array([[0.51492441, 0.22489807, 0.80493126],
       [0.11697984, 0.36975702, 0.33153982]])

In [50]:
#랜덤 값 생성하기2
#(시작, n-1)사이의 랜덤한 정수 1개 생성
np.random.randint(2, 10)

4

In [53]:
#(2, 3) 크기의 랜덤 정수 배열 생성
np.random.randint(2, 10, size=(2, 3))

array([[4, 6, 3],
       [6, 4, 6]])

### array 연산

In [54]:
#파이썬의 list 연산
list1 = [1,2,3]
list2 = [4,5,6]
list1 + list2

[1, 2, 3, 4, 5, 6]

In [58]:
# 파이썬의 list 연산2
list3 = []
for i in range(len(list1)):
    hap = list1[i]+ list2[i]
    list3.append(hap)
list3

[5, 7, 9]

In [68]:
#numpy의 array 연산
arr1 = np.array(list1)
arr2 = np.array(list2)
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 % arr2)
print(arr1 // arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 2 3]
[0 0 0]


### array 배열의 인덱싱, 슬라이싱

#### - 인덱싱

In [70]:
arr = np.array([[1,2,3], [4,5,6]])
arr
arr[0][0]

1

In [72]:
#특정 행, 열 인덱싱1
#숫자2
arr[0][1]

2

In [73]:
#특정 행, 열 인덱싱2
arr[0, 1]

2

#### - 슬라이싱

In [78]:
# 0~9까지 담긴 1차원 배열
arr1 = np.arange(10)
arr1[3:6]

array([3, 4, 5])

In [80]:
# 2차원 배열 슬라이싱
# 0~49 배열 생성
arr2 = np.arange(50)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [104]:
# reshape() 함수 - 배열의 크기 다시 지정 (반드시 재지정하려는 배열의 개수가 같아야 함.)
# [행의 범위, 열의 범위]
arr2 = np.arange(50).reshape(5,10)
print(arr2)
arr2[:4, : 5]
arr2[2][3]

arr2[2][1], arr2[2][3]
arr2[(2, 2), (1, 3)]

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


array([21, 23])

### BMI 구하기

In [114]:
#('파일명.확장자', '구분 기호')
# delimiter : 구분 기호
data = np.loadtxt('height_weight.txt', delimiter=',')
data

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

In [116]:
#1. 데이터를 키와 몸무게로 나누기
height = data[0]
weight = data[1]

array([65.6, 88. , 79.2, 69.3, 55. , 71.2, 73. , 68.9, 74. , 82. ])

In [128]:
#2. 키 단위 변경( cm -> m)
# 나누기 100 or 곱하기 0.01
height_m = height/100

In [132]:
#3. BMI 연산
bmi = weight/(height_m*height_m)
bmi

array([21.37153104, 27.07018468, 25.86122449, 24.20652885, 16.03543423,
       20.14486193, 23.14392095, 21.69720651, 23.62028791, 25.59220998])

### Boolean 인덱싱
- Boolean : True/False
- True 값은 출력
- False 값은 출력하지 않음

In [7]:

name = np.array(['철수', '영수', '영희','영철'])
name

array(['철수', '영수', '영희', '영철'], dtype='<U2')

In [8]:
bool = np.array([True, False, True, False])
bool

array([ True, False,  True, False])

In [9]:
name[bool]

array(['철수', '영희'], dtype='<U2')

In [11]:
#데이터 생성
name_score = np.array([['철수', 100],
                     ['영희', 90],
                     ['영수', 80],
                     ['영철', 70]])

In [12]:
name_score

array([['철수', '100'],
       ['영희', '90'],
       ['영수', '80'],
       ['영철', '70']], dtype='<U11')

In [13]:
#영희의 점수?
name_score[1][1]

'90'

In [24]:
#영희의 데이터
#1.이름 데이터만 인덱싱
name_score[:, 0]

array(['철수', '영희', '영수', '영철'], dtype='<U11')

In [25]:
#2. 가져온 데이터에서 '영희'인지 확인
name_score[:, 0] =='영희'# 전체데이터에서 0번째 이름이 영희인 데이터 가져오기
#불리언

array([False,  True, False, False])

In [26]:
#3. 조건에 따라 데이터 가져오기(인덱싱)
name_score[name_score[:,0]=='영희'] # 전체데이터에서 영희인 데이터만 출력

array([['영희', '90']], dtype='<U11')

### 다양한 함수들

In [34]:
# 1~10까지 담긴 1차원 배열 생성
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
# 위에서 생성한 배열을 (2, 5) 크기로 바꿔주기
arr = arr.reshape(2, 5)

In [38]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [43]:
# np.sum() : 더하기 함수
print("요소 전체 더하기 : ", np.sum(arr))
print("세로 방향으로 더하기 : ",np.sum(arr, axis=0)) # axis = 0 : 세로축
print("가로 방향으로 더하기 : ",np.sum(arr, axis=1)) # asis= 1 : 가로축

요소 전체 더하기 :  55
세로 방향으로 더하기 :  [ 7  9 11 13 15]
가로 방향으로 더하기 :  [15 40]


In [45]:
#np.mean() : 평균 구하기 함수
np.mean(arr)
print("세로 방향으로 평균구하기 :",np.mean(arr, axis=0))
print("가로 방향으로 평균구하기 :",np.mean(arr, axis=1))

세로 방향으로 평균구하기 : [3.5 4.5 5.5 6.5 7.5]
가로 방향으로 평균구하기 : [3. 8.]


In [48]:
# abs 절댓값 구하기 함수
arr1 = np.array([-1, 2, -3, 4, -5, -6])
np.abs(arr1) # 모두 다 절댓값으로 구하기

array([1, 2, 3, 4, 5, 6])

# 2. Pandas

- 행과 열로 구성된 표 형식의 데이터를 지원하는 라이브러리
- Series Class : 1차원(인덱스 + 값)
- DataFrame Class : 2차원(행과 열을 가지는 표의 형태, 서로 다른 종류의 자료형 저장 가능, 엑셀 같이 생김)

In [49]:
import pandas as pd

### Series 생성

In [53]:
population = pd.Series([9904312, 3448737, 2890451, 2466052])
population

0    9904312
1    3448737
2    2890451
3    2466052
dtype: int64

In [55]:
#인덱스 지정이 가능함
population = pd.Series([9904312, 3448737, 2890451, 2466052],
         index=['서울', '부산','인천', '대구'])
population

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

# 3. Matplotlib
- 2D 그래프로 시각화가 가능한 라이브러리